server:
  port: 8088

spring:
  application:
    name: search-service

  elasticsearch:
    uris: ${SPRING_ELASTICSEARCH_URIS:http://localhost:9200}
    api-key: ${ELASTIC_CLOUD_API_KEY}
    connection-timeout: 10s
    socket-timeout: 60s


  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
    consumer:
      group-id: search-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


elasticsearch:
  index:
    properties: properties_v1

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    com.homeverse.search.kafka.consumer: INFO
    org.springframework.kafka: INFO