server:
  port: 8084
  tomcat:
    max-swallow-size: 50MB

spring:
  application:
    name: media-service

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
  